language: python
python:
  - "2.7"

before_install:
  - pip install codecov

install:
  - pip install -r requirements.txt
  - python setup.py install

script:
  - nosetests --with-coverage

after_success:
  - codecov
