#!/usr/bin/python
from bricklayer.doctor.config import Configurator
from bricklayer.doctor.metrics import Metrics
from bricklayer.backend.api import BackendApi

def main():
    Configurator.create_config_if_doesnt_exist()
    parser = Configurator.generate_parser()
    args = parser.parse_args()
    if args.filename:
        m = Metrics()
        m.collect_metrics(args.filename)
        BackendApi.post_metrics(
            source_lines_of_code=m.source_lines_of_code,
            comments=m.comments,
            cyclomatic_complexity=m.cyclomatic_complexity,
            filename=args.filename,
            user_defined_functions=m.user_defined_functions,
            level=m.level
        )


if __name__ == '__main__':
    main()
